# Generated by Django 6.0 on 2026-02-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Dine In', 'Dine In'), ('Takeaway', 'Takeaway'), ('Delivery', 'Delivery')], default='Dine In', max_length=10),
        ),
    ]
