# Generated by Django 6.0 on 2026-02-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Dine In', 'Dine In'), ('Takeaway', 'Takeaway')], default='Dine In', max_length=10),
        ),
    ]
