# Generated by Django 6.0 on 2026-02-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10, unique=True)),
                ('seats', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Booked', 'Booked')], default='Available', max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
